### ISSUE TITLE
ADC2019ルールについて

### ISSUE THREAD

**Issue by Remonn0** [dasadc/dasadc.github.io#14]
ADC2019のルールを確認したところ気になるところが何点かあるので質問させていただきます．

1. テトリミノ中の数字の無い空欄マスに配線することは可能でしょうか？
2. すべてのマスが空欄となるテトリミノが存在しても大丈夫でしょうか？
3. 例題のフォーマット中のBlock #4の表記方法が間違っていないでしょうか？
4. 問題の回答ルールが3次元となっているのは間違いでしょうか？

お答えいただけると幸いです．

**Comment by Remonn0** [comment]
対応ありがとうございました．

**Comment by ysnt27** [comment]
（まだcommitしてませんが…）


>     テトリミノ中の数字の無い空欄マスに配線することは可能でしょうか？

配線できない、とします。

- '0'の位置は配線不可能
- '*'の位置は配線可能

そういえば、これまで'0'を、線を引かない空白マスとして使っていたので、紛らわしいことになってます。
今さらですが、ルールの表現方法を変更します。

- '0' --> '+' に変更
- '*' --> '0'に変更



>     すべてのマスが空欄となるテトリミノが存在しても大丈夫でしょうか？

すべてが数字なしのマスが、存在してもOKとします。

>     例題のフォーマット中のBlock #4の表記方法が間違っていないでしょうか？

間違っていました。

```
BLOCK#4 2X2
1,2
4,*
```

ではなくて

```
BLOCK#4 2X2
1,2
4,0
```

です。
さらに、上記のように、記号の使い方を変更します。


>     問題の回答ルールが3次元となっているのは間違いでしょうか？



以下の、Z軸に関する記述が、修正漏れでした。

> 回答ルール
...
>     ブロック上の端点の間を交差・分岐の無い配線で接続する
>         配線の端点が存在するマスは、X, Y, Z方向に隣接する最大6個のマスのうち1個と接続される（ナンバーリンクと同じ）
>         配線を構成する端点以外のマスは、X, Y, Z方向に隣接する最大6個のマスのうち2個と接続される（ナンバーリンクと同じ）


-    配線の端点が存在するマスは、X, Y方向に隣接する最大4個のマスのうち1個と接続される（ナンバーリンクと同じ）
-    配線を構成する端点以外のマスは、X, Y方向に隣接する最大4個のマスのうち2個と接続される（ナンバーリンクと同じ）

**Comment by ysnt27** [comment]
Webサイト、更新しました。

https://dasadc.github.io/adc2019/rule.html

**Comment by Remonn0** [comment]
質問への回答ありがとうございました．
ADCのルールで気になるところがあるので再度質問させていただきます．例年では，同時に取り組める問題は一問と認識していますが，今年度は同時に複数の問題に取り組むことは可能なのでしょうか？極端な例として30台のPCを用いてすべての問題に並列に取り組むなどは可能なのでしょうか？

**Comment by ysnt27** [comment]
> 同時に複数の問題に取り組むことは可能なのでしょうか？

実行委員で協議した結果、**複数の問題を並列で解くのはOK**とすることにします。

後ほど、ルールのページに明記します。

**Comment by Remonn0** [comment]
回答と対応ありがとうございました．

**Comment by ysnt27** [comment]
2019年、2020年のアルゴリズムデザインコンテストでは、「これまで'0'を、線を引かない空白マスとして使っていたので、紛らわしいことになって」いたのを、`0'と`+`の違いを無視する特例ルールになっていましたが、2021年では、この`0'と`+`の違いを無視する特例ルールを廃止します。

https://dasadc.github.io/adc2021/rule.html
